export const questionnaire_data = {
  "Category": [
    "General Information", "General Information", "General Information",
    "Market Insights", "Market Insights", "Market Insights",
    "Competitor Analysis", "Competitor Analysis", "Competitor Analysis",
    "Technical Inputs", "Technical Inputs", "Technical Inputs", "Technical Inputs",
    "Financial Inputs", "Financial Inputs", "Financial Inputs", "Financial Inputs", "Financial Inputs", "Financial Inputs",
    "Risk Assessment", "Risk Assessment", "Risk Assessment",
    "Regulatory and Legal Considerations", "Regulatory and Legal Considerations", "Regulatory and Legal Considerations",
    "Operational Inputs", "Operational Inputs", "Operational Inputs",
    "Environmental and Social Impacts", "Environmental and Social Impacts",
    "Supporting Documents"
  ],
  "Question": [
    "Project Name", "Business Objective", "Project Description",
    "Target Market Segment", "Market Size and Opportunity", "Customer Needs or Pain Points",
    "Key Competitors", "Competitor Strategies", "Differentiation Factors",
    "Network Components Required", "Infrastructure Investments Needed", "Technical Challenges and Risks", "Deployment Timeline",
    "Capital Expenditure (CapEx)", "Operational Expenditure (OpEx)", "Expected Revenue", "Profitability Metrics - ROI", 
    "Profitability Metrics - Break-even Point", "Profitability Metrics - NPV",
    "Technical Risks", "Market Risks", "Financial Risks",
    "Licensing Requirements", "Compliance Needs", "Data Privacy and Security",
    "Internal Capabilities", "Vendors and Partners", "Training or Hiring Needs",
    "Environmental Impact", "Social Benefits",
    "Upload Supporting Files"
  ],
  "Description": [
    "Enter the name of the initiative (e.g., '5G FWA Rollout').",
    "Select the primary goal of the project.",
    "Provide a brief overview of the project and its purpose.",
    "Select the target customer base.",
    "Provide the estimated market size and potential growth for this service.",
    "Describe the primary needs or issues this project aims to address.",
    "List the main competitors offering similar services.",
    "Briefly outline competitor pricing, features, or tactics.",
    "What unique value will this project offer compared to competitors?",
    "Choose the relevant network elements.",
    "Detail any hardware, software, or cloud resources required.",
    "Describe potential technical hurdles and mitigation plans.",
    "Provide the expected start and end dates for the project.",
    "Estimate the total upfront costs.",
    "Estimate ongoing costs.",
    "Provide a forecast of expected revenues over the next 3–5 years.",
    "Return on Investment as a percentage.",
    "The time required to recover the investment.",
    "Provide the project's NPV based on cash flow projections.",
    "List any risks related to system failures or performance.",
    "Describe risks such as low demand or competitor response.",
    "Highlight potential cost overruns or funding challenges.",
    "Describe any required licenses or regulatory approvals.",
    "Mention relevant laws or standards.",
    "Detail measures for managing customer data securely.",
    "Does the organization have the required expertise?",
    "List key vendors, contractors, or technology partners.",
    "Specify if additional staff training or hiring is needed.",
    "Outline the potential environmental effects of the project.",
    "Describe how the project will benefit the community.",
    "Attach any additional information, such as market research, technical diagrams, or financial projections."
  ],
  "Input Type": [
    "Text Field", "Dropdown", "Text Field",
    "Dropdown (Multi-select)", "Text Field", "Text Field",
    "Text Field", "Text Field", "Text Field",
    "Dropdown (Multi-select)", "Text Field", "Text Field", "Date Picker",
    "Text Field", "Text Field", "Text Field", "Text Field", 
    "Text Field", "Text Field",
    "Text Field", "Text Field", "Text Field",
    "Text Field", "Text Field", "Text Field",
    "Dropdown", "Text Field", "Text Field",
    "Text Field", "Text Field",
    "File Upload Field"
  ]
};